SQL:
  Type: SQLITE
  Host: /
  Database: /
  Username: /
  Password: /
  Port: /

translation: en

command-aliases: ["pa", "party", "mcmmoparty"]

force-disable:
  native-mcmmo-parties: true
  native-mythicdungeons-party: true

Network:
  ServerName: paper
  TeleportChannel: "mcmmoparties:teleport"
  PartyChatChannel: "mcmmoparties:partychat"

Commands:
  OverrideMcMMOPartyCommand: true
  OverrideMythicDungeonsCommand: true

Hooks:
  ChestShop:
    Enabled: true

DungeonInstance:
  DefaultSlots: 2

Party:
  BaseMemberSlots: 10
  MaxPartiesPerPlayer: 3 # Set to -1 for unlimited simultaneous party memberships.
  PartyLevelCap: 100 # Set to -1 for unlimited party levels.
  DefaultTresorSize: 50000

Invitations:
  ExpirationHours: 24

Buffs:
  Handler: SKILLPOINTS
  SkillPointsPerLevel: 1

Experience:
  LevelCurve: "(x * (20 + (2.5 * x))) * 25"
  Bar:
    Color: BLUE
    Segments: SOLID
  Scaling:
    MINING: 0.10
    WOODCUTTING: 0.10
    REPAIR: 0.04
    UNARMED: 0.09
    HERBALISM: 0.09
    EXCAVATION: 0.10
    ARCHERY: 0.09
    SWORDS: 0.09
    AXES: 0.09
    ACROBATICS: 0.03
    TAMING: 0.05
    FISHING: 0.07
    ALCHEMY: 0.05
    SMELTING: 0.04
    SALVAGE: 0.03
    MACES: 0.09
    TRIDENTS: 0.08
    CROSSBOWS: 0.08
    SPEARS: 0.08
