SQL:
  Type: LOCALE
  Host: /
  Database: /
  Username: /
  Password: /
  Port: /

Party:
  BaseMemberSlots: 10

Buffs:
  Handler: LEVEL
  SkillPointsPerLevel: 1
  DisplayNames:
    EXP_SHARING_RATE: "&aExp Sharing Rate"
    EXP_SHARING_RADIUS: "&aExp Sharing Radius"
    MEMBER_SLOTS: "&aMember Slots"
    ABILITY_DURATION: "&aAbility Duration"
