SQL:
  Type: LOCALE
  Host: /
  Database: /
  Username: /
  Password: /
  Port: /

Network:
  ServerName: paper
  TeleportChannel: "mcmmoparties:teleport"
  PartyChatChannel: "mcmmoparties:partychat"

Commands:
  OverrideMcMMOPartyCommand: true
  OverrideMythicDungeonsCommand: true

Hooks:
  ChestShop:
    Enabled: true

DungeonInstance:
  DefaultSlots: 3

Party:
  BaseMemberSlots: 10

Buffs:
  Handler: LEVEL
  SkillPointsPerLevel: 1
  DisplayNames:
    EXP_SHARING_RATE: "&aExp Sharing Rate"
    EXP_SHARING_RADIUS: "&aExp Sharing Radius"
    MEMBER_SLOTS: "&aMember Slots"
    ABILITY_DURATION: "&aAbility Duration"
    ABILITY_COOLDOWN_REDUCTION: "&aAbility Cooldown Reduction"
    DUNGEON_INSTANCE_SLOTS: "&aDungeon Instance Slots"

Skills:
  DisplayNames:
    MINING: "Mining"
    WOODCUTTING: "Woodcutting"
    REPAIR: "Repair"
    UNARMED: "Unarmed"
    HERBALISM: "Herbalism"
    EXCAVATION: "Excavation"
    ARCHERY: "Archery"
    SWORDS: "Swords"
    AXES: "Axes"
    ACROBATICS: "Acrobatics"
    TAMING: "Taming"
    FISHING: "Fishing"
    ALCHEMY: "Alchemy"
    SMELTING: "Smelting"
    SALVAGE: "Salvage"
    MACES: "Maces"
    TRIDENTS: "Tridents"
    CROSSBOWS: "Crossbows"
    SPEARS: "Spears"

Experience:
  LevelCurve: "x * 50 * Math.pow(x,2)"
  Bar:
    Display: "&b%party%     &9LvL &b%level%     &7[&a%exp%&7/&a%needed%&7]"
    Color: BLUE
    Segments: SOLID
  Scaling:
    MINING: 0.2
    WOODCUTTING: 0.2
    REPAIR: 0.2
    UNARMED: 0.2
    HERBALISM: 0.2
    EXCAVATION: 0.2
    ARCHERY: 0.2
    SWORDS: 0.2
    AXES: 0.2
    ACROBATICS: 0.2
    TAMING: 0.2
    FISHING: 0.2
    ALCHEMY: 0.2
    SMELTING: 0.2
    SALVAGE: 0.2
    MACES: 0.2
    TRIDENTS: 0.2
    CROSSBOWS: 0.2
    SPEARS: 0.2
