name: McMMOParties
version: '${project.version}'
main: net.maksy.mcmmoparties.McMMOParties
api-version: 1.21
authors: [ MaksyKun ]
commands:
  party:
    description: Party command
    usage: /party
    aliases:
      - pa