package net.maksy.mcmmoparties.configuration.enums;

public enum Lang {
    PARTY_ALREADY_EXISTS,
    PARTY_NOT_EXISTS,
    PARTY_CHAR_LIMIT,
    ALREADY_IN_PARTY,
    ALREADY_REQUESTING,
    PARTY_KICKED,
    PARTY_LEFT,
    CANT_KICK_SELF,
    NOT_MEMBER,
    NOT_REQUESTING,
    NOT_IN_PARTY,
    NOT_A_NUMBER,
    NOT_OWNER,
    NEW_OWNER,
    REQUEST_SEND,
    PARTY_CREATED,
    PARTY_UPDATED,
    PARTY_JOINED,
    PARTY_LEVELUP,
    PARTY_DISBANDED,
    OWNER_CANNOT_LEAVE,
    WAYPOINT_NOT_SET,
    WAYPOINT_UPDATED,

    PLAYER_NOT_EXISTS;
}
